package com.mh.entity;

import java.util.Date;

public class TMatchMessage {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_match_message.id
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_match_message.date
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    private Date date;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_match_message.content
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    private String content;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_match_message.ctype
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    private Integer ctype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_match_message.create_time
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    private Date createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_match_message.modify_time
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    private Date modifyTime;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_match_message.id
     *
     * @return the value of t_match_message.id
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_match_message.id
     *
     * @param id the value for t_match_message.id
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_match_message.date
     *
     * @return the value of t_match_message.date
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_match_message.date
     *
     * @param date the value for t_match_message.date
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_match_message.content
     *
     * @return the value of t_match_message.content
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_match_message.content
     *
     * @param content the value for t_match_message.content
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_match_message.ctype
     *
     * @return the value of t_match_message.ctype
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    public Integer getCtype() {
        return ctype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_match_message.ctype
     *
     * @param ctype the value for t_match_message.ctype
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    public void setCtype(Integer ctype) {
        this.ctype = ctype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_match_message.create_time
     *
     * @return the value of t_match_message.create_time
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_match_message.create_time
     *
     * @param createTime the value for t_match_message.create_time
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_match_message.modify_time
     *
     * @return the value of t_match_message.modify_time
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_match_message.modify_time
     *
     * @param modifyTime the value for t_match_message.modify_time
     *
     * @abatorgenerated Sun Aug 30 09:46:40 EDT 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

	@Override
	public String toString() {
		return "TMatchMessage [id=" + id + ", date=" + date + ", content="
				+ content + ", ctype=" + ctype + ", createTime=" + createTime
				+ ", modifyTime=" + modifyTime + "]";
	}
    
    
}