/**   
* 文件名称: WebNtElectronic.java<br/>
* 版本号: V1.0<br/>   
* 创建人: Channel<br/>  
* 创建时间 : 2015-6-30 下午2:11:36<br/>
*/  
package com.mh.entity;


/** 
 * 类描述: TODO<br/>新nt电子游戏记录表
 * 创建人: TODO Channel<br/>
 * 创建时间: 2015-6-30 下午2:11:36<br/>
 */
public class WebNewNtElectronic{
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_web_newnt_electronic.id
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_web_newnt_electronic.ele_game_id
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    private String eleGameId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_web_newnt_electronic.ele_game_code
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    private String eleGameCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_web_newnt_electronic.ele_game_cnname
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    private String eleGameCnname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_web_newnt_electronic.ele_game_enname
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    private String eleGameEnname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_web_newnt_electronic.ele_game_pic
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    private String eleGamePic;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_web_newnt_electronic.ele_game_type1
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    private String eleGameType1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_web_newnt_electronic.ele_game_type2
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    private String eleGameType2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_web_newnt_electronic.ele_game_active
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    private Integer eleGameActive;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_web_newnt_electronic.ele_index
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    private Integer eleIndex;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_web_newnt_electronic.ele_item2
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    private String eleItem2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_web_newnt_electronic.is_water
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    private Integer isWater;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_web_newnt_electronic.status
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_web_newnt_electronic.remark
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    private String remark;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_web_newnt_electronic.ele_hot_num
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    private Integer eleHotNum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_web_newnt_electronic.ele_is_new
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    private Integer eleIsNew;
    
    private Integer isFavourite;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_web_newnt_electronic.id
     *
     * @return the value of t_web_newnt_electronic.id
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_web_newnt_electronic.id
     *
     * @param id the value for t_web_newnt_electronic.id
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_web_newnt_electronic.ele_game_id
     *
     * @return the value of t_web_newnt_electronic.ele_game_id
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public String getEleGameId() {
        return eleGameId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_web_newnt_electronic.ele_game_id
     *
     * @param eleGameId the value for t_web_newnt_electronic.ele_game_id
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public void setEleGameId(String eleGameId) {
        this.eleGameId = eleGameId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_web_newnt_electronic.ele_game_code
     *
     * @return the value of t_web_newnt_electronic.ele_game_code
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public String getEleGameCode() {
        return eleGameCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_web_newnt_electronic.ele_game_code
     *
     * @param eleGameCode the value for t_web_newnt_electronic.ele_game_code
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public void setEleGameCode(String eleGameCode) {
        this.eleGameCode = eleGameCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_web_newnt_electronic.ele_game_cnname
     *
     * @return the value of t_web_newnt_electronic.ele_game_cnname
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public String getEleGameCnname() {
        return eleGameCnname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_web_newnt_electronic.ele_game_cnname
     *
     * @param eleGameCnname the value for t_web_newnt_electronic.ele_game_cnname
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public void setEleGameCnname(String eleGameCnname) {
        this.eleGameCnname = eleGameCnname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_web_newnt_electronic.ele_game_enname
     *
     * @return the value of t_web_newnt_electronic.ele_game_enname
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public String getEleGameEnname() {
        return eleGameEnname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_web_newnt_electronic.ele_game_enname
     *
     * @param eleGameEnname the value for t_web_newnt_electronic.ele_game_enname
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public void setEleGameEnname(String eleGameEnname) {
        this.eleGameEnname = eleGameEnname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_web_newnt_electronic.ele_game_pic
     *
     * @return the value of t_web_newnt_electronic.ele_game_pic
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public String getEleGamePic() {
        return eleGamePic;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_web_newnt_electronic.ele_game_pic
     *
     * @param eleGamePic the value for t_web_newnt_electronic.ele_game_pic
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public void setEleGamePic(String eleGamePic) {
        this.eleGamePic = eleGamePic;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_web_newnt_electronic.ele_game_type1
     *
     * @return the value of t_web_newnt_electronic.ele_game_type1
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public String getEleGameType1() {
        return eleGameType1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_web_newnt_electronic.ele_game_type1
     *
     * @param eleGameType1 the value for t_web_newnt_electronic.ele_game_type1
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public void setEleGameType1(String eleGameType1) {
        this.eleGameType1 = eleGameType1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_web_newnt_electronic.ele_game_type2
     *
     * @return the value of t_web_newnt_electronic.ele_game_type2
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public String getEleGameType2() {
        return eleGameType2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_web_newnt_electronic.ele_game_type2
     *
     * @param eleGameType2 the value for t_web_newnt_electronic.ele_game_type2
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public void setEleGameType2(String eleGameType2) {
        this.eleGameType2 = eleGameType2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_web_newnt_electronic.ele_game_active
     *
     * @return the value of t_web_newnt_electronic.ele_game_active
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public Integer getEleGameActive() {
        return eleGameActive;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_web_newnt_electronic.ele_game_active
     *
     * @param eleGameActive the value for t_web_newnt_electronic.ele_game_active
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public void setEleGameActive(Integer eleGameActive) {
        this.eleGameActive = eleGameActive;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_web_newnt_electronic.ele_index
     *
     * @return the value of t_web_newnt_electronic.ele_index
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public Integer getEleIndex() {
        return eleIndex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_web_newnt_electronic.ele_index
     *
     * @param eleIndex the value for t_web_newnt_electronic.ele_index
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public void setEleIndex(Integer eleIndex) {
        this.eleIndex = eleIndex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_web_newnt_electronic.ele_item2
     *
     * @return the value of t_web_newnt_electronic.ele_item2
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public String getEleItem2() {
        return eleItem2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_web_newnt_electronic.ele_item2
     *
     * @param eleItem2 the value for t_web_newnt_electronic.ele_item2
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public void setEleItem2(String eleItem2) {
        this.eleItem2 = eleItem2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_web_newnt_electronic.is_water
     *
     * @return the value of t_web_newnt_electronic.is_water
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public Integer getIsWater() {
        return isWater;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_web_newnt_electronic.is_water
     *
     * @param isWater the value for t_web_newnt_electronic.is_water
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public void setIsWater(Integer isWater) {
        this.isWater = isWater;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_web_newnt_electronic.status
     *
     * @return the value of t_web_newnt_electronic.status
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_web_newnt_electronic.status
     *
     * @param status the value for t_web_newnt_electronic.status
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_web_newnt_electronic.remark
     *
     * @return the value of t_web_newnt_electronic.remark
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_web_newnt_electronic.remark
     *
     * @param remark the value for t_web_newnt_electronic.remark
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_web_newnt_electronic.ele_hot_num
     *
     * @return the value of t_web_newnt_electronic.ele_hot_num
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public Integer getEleHotNum() {
        return eleHotNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_web_newnt_electronic.ele_hot_num
     *
     * @param eleHotNum the value for t_web_newnt_electronic.ele_hot_num
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public void setEleHotNum(Integer eleHotNum) {
        this.eleHotNum = eleHotNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_web_newnt_electronic.ele_is_new
     *
     * @return the value of t_web_newnt_electronic.ele_is_new
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public Integer getEleIsNew() {
        return eleIsNew;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_web_newnt_electronic.ele_is_new
     *
     * @param eleIsNew the value for t_web_newnt_electronic.ele_is_new
     *
     * @abatorgenerated Tue Dec 13 13:20:15 CST 2016
     */
    public void setEleIsNew(Integer eleIsNew) {
        this.eleIsNew = eleIsNew;
    }

	public Integer getIsFavourite() {
		return isFavourite;
	}

	public void setIsFavourite(Integer isFavourite) {
		this.isFavourite = isFavourite;
	}
}
